root = "."
tmp_dir = "tmp"
env_files = [".env"]

[build]
cmd = "go build -gcflags=all=\"-N -l\" -o ./tmp/main ."
entrypoint = [
  "dlv", "exec", "--listen=127.0.0.1:2345", "--headless", "--api-version=2",
  "--accept-multiclient", "--continue", "./tmp/main", "serve",
]
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["tmp", "vendor", "api-docs"]
exclude_regex = ["_test\\.go"]
stop_on_error = true

[log]
time = false

[misc]
clean_on_exit = true
